version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      -27018:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc@123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: abc@123
      ME_CONFIG_MONGODB_URL: mongodb://root:abc@123@mongo:27017/
